language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false
  slack:
    secure: Qjr3Z9nDgeB6LKVfit3cUWb5p+Rc/kNml1hbO9caIni4o2UiQrjWYHl1c9sj++OdNWghfS0VkCijKS+PtdInyj0bVRouWO8SMsrSeUhWd5QiQNoqJpCDFR6N4K8ZKs3zsGtGkji8ZSEPr9x50IbadqW5JiU172ULesZkjsSJdnw=
